### ISSUE TITLE
server build faild 'multiple definition'

### ISSUE THREAD

**Issue by Garefild** [doronz88/rpc-project#219]
**Test environment**
- Ubuntu 22.04 LTS

**Describe the bug**
build the RPC-Server failed.

**Logs**
![log](https://user-images.githubusercontent.com/2126092/188249572-a9f596ff-2438-4513-a7fe-59aed8299dfe.png)

**Additional context**
fix using an 'extern' in common.h.
>I am unsure if this is the right way to fix the issue.

```c++
extern bool g_stdout;
extern bool g_syslog;
extern FILE *g_file;
```

**Comment by doronz88** [comment]
Thanks for creating the issue! Can you verify latest release (v3.11.1) now solves the issue?

**Comment by Garefild** [comment]
You’re on the right track now!
Keep up the great work!
