### ISSUE TITLE
Guide for rpc service

### ISSUE THREAD

**Issue by Dantee296** [doronz88/rpc-project#230]
hi , can you please provide a example guide for using this rpc service

ex. how we can call native methods and get information from it
let say i wanna get info about **"HID simulation (p.hid.*)"**

**Comment by doronz88** [comment]
What part exactly do you feel wasn't explained enough? The build? The usage?

**Comment by Dantee296** [comment]
i feel usage part with some examples specially for iOS
ex 

**iOS Only:**
MobileGestalt (p.mobile_gestalt.*)
Backlight adjusting (p.backlight.*)

**Comment by doronz88** [comment]
I need to understand what isn't explained enough.
Did you view the [quickstart](https://github.com/doronz88/rpc-project#quickstart)?

If so, what part did not work for you? execution on the remote device? connecting to it via the python client?
After you just executed what was written you should have got an IPython shell which just lets you call whatever C native API you desire.
